# Generated by Django 5.1.6 on 2025-03-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_presentes_api', '0002_presente_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presente',
            name='link',
            field=models.CharField(max_length=350),
        ),
    ]
