# Generated by Django 5.1.6 on 2025-03-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_presentes_api', '0003_alter_presente_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='convidado',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
