# Generated by Django 5.1.6 on 2025-03-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_presentes_api', '0004_convidado_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presente',
            name='image',
            field=models.ImageField(upload_to='presentes/'),
        ),
    ]
