# Generated by Django 5.1.6 on 2025-03-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_presentes_api', '0005_alter_presente_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presente',
            name='image',
            field=models.ImageField(null=True, upload_to='presentes/'),
        ),
    ]
